### ISSUE TITLE
qri list with no datasets doesn't show username

### ISSUE THREAD

**Issue by chriswhong** [qri-io/qri#1069]
qri list with no datasets yields ` has no datasets`.  The username is not shown.

**Comment by advanderveer** [comment]
I ran into this a few minutes ago. I took a quick look at the code and the situation is triggered because the `--peer` argument's value is used directly in the feedback string. When the `list` command is run without that argument it will be empty and trigger the bug. 

I can contribute a quick fix that changes the message to `you have no datasets` when the `--peer` argument is not provided. Let me know if you like that idea, then i'll setup a PR for it.

**Comment by dustmop** [comment]
Hi @advanderveer! This would be great. It's probably a relatively simple change, and we would appreciate the fix. Make sure you run the unit tests using `go test ./...` when you do so.

**Comment by advanderveer** [comment]
@dustmop I setup a PR https://github.com/qri-io/qri/pull/1151, we can continue the discussion there

**Comment by dustmop** [comment]
Issue fixed by https://github.com/qri-io/qri/pull/1151, thanks @advanderveer!
