### ISSUE TITLE
Qri Desktop crashes frequently with a blank screen

### ISSUE THREAD

**Issue by sgammon** [qri-io/qri#1110]
When using Qri Desktop, I have a dataset I setup through the CLI. Clicking on the "Body" screen crashes the app and displays a blank UI. Henceforth, when I open Qri Desktop, clicking on my dataset at all crashes the app with the same behavior (presumably because it is defaulting to the _Body_ screen still).

This also happens if I click the "Dataset - work with the active dataset" button on the top left in the navigation.

Qri Desktop version: Reports `0.9.4` for the backend
Qri CLI version: Reports `0.9.5-dev`

After examining the debug log, I don't see any "errors," per-se, but I'm happy to share it nonetheless.

Here's what I mean by "crash"/"blank UI":
<img width="989" alt="Screen Shot 2020-02-10 at 12 57 08 PM" src="https://user-images.githubusercontent.com/171897/74189203-da0bad80-4c04-11ea-9fdd-abf4e16c2bbf.png">

**Comment by dustmop** [comment]
I'm pretty sure this a bug on Desktop caused by a json formatted body. Though json works (except as noted in https://github.com/qri-io/qri/issues/1114) on the backend, it's not currently a "first-class" citizen in Desktop, and it looks like a regression crept in. We should at least we showing a reasonable error message for this situation, and have a test that verifies as much.

**Comment by b5** [comment]
Thanks to this issue, we shipped qri-io/desktop#465, which now shows a crash report instead of a blank screen.
