### ISSUE TITLE
Qri takes ages when loading a large file as a body

### ISSUE THREAD

**Issue by sgammon** [qri-io/qri#1112]
I tried adding a dataset to Qri, but the dataset is modestly large (~7GB or so), and Qri seems to have serious trouble with it. It seems like it is parsing the whole dataset, or trying to do something with the whole dataset, while setting up my project - because it takes forever.

The file I'm adding is in CSV format, and is well-formed, so there is no need to parse it except to infer structure, which should be an optional feature anyway. There are a handful of columns (certainly less than 10), all with simple types (strings, numbers).

Is this a bug or expected behavior?

**Comment by b5** [comment]
Hey @sgammon, thanks so much for filing. At the moment 7Gigs is on the high end of what Qri can handle, so sadly yes this is somewhat expected. but given that you're doing it, we should start the work of bringing those times down.

I'd love to focus on making _the things you actually want to do_ faster by defining a bare-bones workflow that would be useful to you. We're long overdue for a set of benchmarks, an 8Gig, 10 column CSV of basic types sounds like a great place to start.

I'd love to start with a basic set of benchmarks for a dataset of that size for the following methods before even moving on to fixes.
* `qri save` - creating a new dataset. _lots_ we can clean up here
* `qri get body` - this should only fetch the first 100 rows. No reason this shouldn't be snappy
* `qri get meta` - this shouldn't touch body data at all, and again should be snappy

Once we have those in place, we can actually tell you when qri will meet your expectations for a 7 gig dataset, and keep things that way moving forward.

**Comment by sgammon** [comment]
@b5 candidly, this is deeply confusing to me as a user. i would love to help fix this issue however i can, including benchmarks or a sample dataset.

in terms of dataset use cases i have in front of me, that i would love to use with Qri, i have:
1) small samples less than 10gb, used for ad-hoc querying (these are not very useful)
2) datasets at or above 10gb of CSV and JSON
3) this set is a sample of a larger dataset, i have omitted maybe 30 columns but it does hold all rows

in my world, the above profile is fairly typical, and i was under the impression (perhaps mistaken) that these were small datasets. if Qri can't handle files ~5gb or larger, what datasets is it meant for? i am only wondering if i am a good candidate to use the tool.

i found Qri from the Bazel universe, so i think that's why i thought almost immediately that it would handle files of arbitrary size out of the box. perhaps that's my mistake as a user.

on the commands you mentioned, i presume i can just run `time <cmd>` for each and report back the results? would that be sufficient, or do you have a more detailed idea in mind for benchmarks?

**Comment by sgammon** [comment]
@b5, so, i performed the benchmarks as i described. i decided to create a few samples to give us a range of data

my benchmark data was composed, in each case, of the following:
- ~11MB, or the first 10,000 records of my original CSV (`sample_10k`)
- ~55MB, or the first 50,000 records of my original CSV (`sample_50k`)
- ~110MB, or the first 100,000 records of my original CSV (`sample_100k`)
- ~545MB, or the first 500,000 records of my original CSV (`sample_500k`)
- ~1GB, or the first 1mm records of my original CSV (`sample_1m`)

since the data is highly uniform row-by-row, it scales almost linearly between data size and row count.

this is how i compiled the samples:
<img width="761" alt="Screen Shot 2020-02-11 at 11 41 12 PM" src="https://user-images.githubusercontent.com/171897/74313167-053aed80-4d28-11ea-92bf-5548409a8738.png">

then, i ran the following set of commands against each one, prefixed by `time` (after being snagged by #1116):
- `time qri init --source-body-path <path-to-data> --format CSV --log-all --name <name>`
- `echo "Hello testing testing" > readme.md && time qri save --title "Add readme"`
- `time qri get body`
- `time qri get meta`

here are the results I observed (results reduced from `user / system / cpu / total`):

| Dataset  | `init` | `save` | `get body` | `get meta` |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| `10k`  | `0.97s, 0.09s, 138%, 0.764`  | `2.26s, 0.18s, 132%, 1.840`  | `0.70s, 0.11s, 24%, 3.256`  | `0.03s, 0.03s, 4%, 1.407`  |
| `50k`  | `4.79s, 0.38s, 155%, 3.327`  | `11.35s, 1.01s, 118%, 10.457` | `2.99s, 0.29s, 89%, 3.675`  | `0.03s, 0.02s, 2%, 1.937`  |
| `100k`  | `10.35s, 0.85s, 153%, 7.288`  | `22.82s, 1.93s, 127%, 19.352`  | `5.87s, 0.38s, 90%, 6.915`  | `0.04s, 0.03s, 5%, 1.226`  |
| `500k`  | `53.19s, 5.86s, 152%, 38.747`  | `119.26s, 11.23s, 136%, 1:35.72`  | `27.86s, 1.31s, 97%, 30.039`  | `0.03s, 0.02s, 7%, 0.767`  |
| `1m`  | `109.26s, 26.28s, 156%, 1:26.50`  | `252.76s, 40.52s, 140%, 3:32.67`  | `59.83s, 3.17s, 99%, 1:03.61`  | `0.03s, 0.02s, 9%, 0.565`  |

fully realizing that the above doesn't tell much of a story, i've [created a small Qri dataset to share the data](https://qri.cloud/sgammon/benchmarks). with it, i also produced the following charts:

<img width="598" alt="Screen Shot 2020-02-12 at 1 09 16 AM" src="https://user-images.githubusercontent.com/171897/74320288-37068100-4d35-11ea-87bb-ab8aa7e9d8b5.png">

i hope the above data helps-

**Comment by b5** [comment]
### How Big is "Big"?

> if Qri can't handle files ~5gb or larger, what datasets is it meant for? i am only wondering if i am a good candidate to use the tool.

The use case we've been focused on solving "data portal" type datasets. Some examples:

| title | size | url |
| --- | --- | --- |
| World Bank Population | < 1MB | https://data.worldbank.org/indicator/SP.POP.TOTL | 
| New York City Bicycle Counters | 75MB  | https://data.cityofnewyork.us/Transportation/Bicycle-Counters/smn3-rzf9 | 
| Measurement MobiPerf Data | ~300MB per year | https://www.measurementlab.net/data/ |

All of these are small data publications that change often, and without a meaningful notification. We think the value of a tight audit trail for versioning, enhancing & sharing is clear here. This is also the use case we're best able to solve today. It's generally a many-small-dataset problem, where it's reasonable to keep around versions & rely on basic content addressing as a deduplication strategy between versions.

As you can clearly see based on tests and the size of datasets I'm citing, we're not yet performant enough for your use case. we _very much_ want you to see Qri as a tool you can use for datasets of any size, but we aren't there yet. My understanding of what one would want to do with a 10 gig dataset is somewhat different than this "data portal" use case.

As we move up into (what is in my view) "bigger" data in the 5-25gig-per-version range, the versioning strategy should shift. We should be reverting to storing deltas instead of raw data. We should also provide different retention options like keeping metadata & statistics, but not necessarily storing all data for all versions. There are more things we need to get right before this kind of thing is a reality.

### When Will Qri work for My Use Case?

> i found Qri from the Bazel universe, so i think that's why i thought almost immediately that it would handle files of arbitrary size out of the box. perhaps that's my mistake as a user.

This definitely isn't your mistake as a user. We haven't properly conveyed this in documentation. We've been stuck on getting the answer out because the answer to "how big is too big" is a chart, namely _the chart you've built!_

I think the answer is a chart because there are (very few) folks who are willing to wait 4.2 minutes to save a 1 gig dataset if it gets them decentralized, versioned data. For the vast majority of folks this isn't the case, but a chart answers that question the fastest. In an ideal world we have up-to-date charts documenting our current performance characteristics so others can judge for themselves if Qri works for their data.

### Next Steps

I'm going to work on turning the process you ran into a continuous integration task that can check the performance of each commit to master, and call this issue closable once that's up.

 It'll bring us one step closer my goal of having what the folks at the [deno](https://deno.land) have built, but for our project project: https://deno.land/benchmarks
