### ISSUE TITLE
Fix misspelling of the world "Collisions" in context.go comment 

### ISSUE THREAD

**Issue by swam92** [qri-io/qri#1189]
There is a minor misspelling in the source file qri/api/context.go. The word "collissions" on line 14 should be changed to "collisions".

**Comment by swam92** [comment]
@dustmop Thanks. I have opened up a branch locally named _1189-fix-spelling-of-collisions_ that addresses this change, but when I run "git push origin 1189-fix-spelling-of-collisions" I get the following message : 

> remote: Permission to qri-io/qri.git denied to swam92.
fatal: unable to access 'https://github.com/qri-io/qri.git/': The requested URL returned error: 403

Is there something I am missing that is required to push remotely/open pull requests?

**Comment by dustmop** [comment]
By default, users can't push commits to repositories that they don't have write access to. In order to create a Pull Request, you'll need to fork the repository and push to your own fork. Check out these links for more information:
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork
https://gist.github.com/Chaser324/ce0505fbed06b947d962

Looking forward to your Pull Request, thanks!

**Comment by sesam** [comment]
@swam92 Hey, where have you gone? :)

**Comment by jcardoz** [comment]
@sesam - I can take this up

**Comment by dustmop** [comment]
This has already been fixed, by https://github.com/qri-io/qri/pull/1561
