### ISSUE TITLE
qri sometimes ends up with registry.location=http://127.0.0.1:63086

### ISSUE THREAD

**Issue by Arqu** [qri-io/qri#1196]
After some time qri started showing 500 errors not being able to connect to `http://127.0.0.1:63086`. 
Running `qri config get registry.location` shows this and `qri config set registry.location https://registry.qri.cloud` is a quick manual fix for this.

Initial comments pointed that running the tests might set it to the wrong address but subsequent runs didn't confirm this. Also verified that I hadn't manually changed the config.

**Comment by b5** [comment]
After some discussion, we've come to realize this happens if you run the test suite while `qri connect` is running. This is a variation of a problem we've come to call _fred your repo_ 

> “fred your repo” is a term of art for qri devs. It happens when you run the `e2e` tests in desktop, but leave qri connect running. it’ll change your peername to fred

I vote we re-title this issue to "tests modify local repo data if qri connect is running", and focus on solving that issue properly.

**Comment by b5** [comment]
Labeling this as stale, I think it's been fixed by a number of anti-repo-fredding pieces in qri desktop
