### ISSUE TITLE
fetch doesn't return the commit message & title as history does

### ISSUE THREAD

**Issue by Arqu** [qri-io/qri#1218]
History:
```
[{
  versionInfo: { path: 'qmfoo', ... }
  commitMessage: 'foo',
  commitTitle: 'bar'
}]
```
Fetch:
`[{ 'path': 'qmfoo', ...}]`

**Comment by dustmop** [comment]
Something I missed in the original review: in base/log.go, we have this:

```
type DatasetLogItem struct {
	// Decription of a dataset reference
	dsref.VersionInfo `json:"versionInfo,omitempty"`
    ....
```

If you get rid of the json annotation and change that part to:


```
type DatasetLogItem struct {
	// Decription of a dataset reference
	dsref.VersionInfo
    ....
```

then the api will instead output this json:

```
[{
  path: 'qmfoo',
  ...
  commitMessage: 'foo',
  commitTitle: 'bar'
}]
```

In other words it properly embeds the substructure into itself, instead of nesting it down a level. That makes it much easier to use in Desktop and to convert between DatasetLogItem and VersionInfo. This is a big part of the reason why I was saying we should have tests similar to `TestCheckoutAndRestore` that actually show what the json is expected to look like.
