### ISSUE TITLE
qri status only works in the current directory, --help says you can provide dataset argument

### ISSUE THREAD

**Issue by Arqu** [qri-io/qri#1246]
Running `qri status me/whatever` gives `can only get status of the current working directory` while `qri status --help`gives:
```
qri status --help
List what components and files of the working directory's dataset have been
added, removed, or changed.

If you specify a DATASET, this will list what components were changed in a
particular commit (or the latest commit if none is specified). You can specify
a commit alongside a dataset like:

    me/dataset_name@/ipfs/Qmu...

Usage:
  qri status [DATASET] [flags]

Examples:
  # List what components in the working directory have changed:
  $ qri status
  
  # List what changed in version /ipfs/Qmuabcd of me/my_dataset:
  $ qri status me/my_dataset@/ipfs/Qmuabcd
  
  # List what changed in the latest commit of the working directory:
  $ qri status $(cat .qri-ref)

```

The behavior is correct, but the docs are out of sync.

**Comment by dustmop** [comment]
My fault, didn't update the docs when I modified `status`. But there's another problem: right now `qri status` only works in the current directory with no dataset reference. We should allow `qri status me/my_ds` regardless of directory to get the status of any dataset you own. That's how the api call operates (because it has no "current directory" concept). I got lazy when splitting out the `whatchanged` command and forgot to handle this case for command-line.
