### ISSUE TITLE
bug(Log): no way to explicitly skip local search to search on registry

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#1328]
Caught this bug running the e2e desktop app tests, which continue to pay dividends.

We have 2 pieces of info from the user that lets us determine where to search for a given log,  a boolean `local` flag and a string `remote` flag.

Currently, we are only paying attention to the local flag when it is `true`, if it is true, and we get a `repo: not found` error, we know the user wanted to only search locally & that the dataset does not exist in the local repo.

If the user has a specific `remote` flag set, then we know the user explicitly does not want to search locally, and instead wants us to search the remote. We skip any local search and go directly for a network search.

However, in our codebase, the empty string "" is what indicates in the `lib.Fetch` that the user wants to search the registry. 

That should mean that if the user has no remote, it will search the registry. BUT if a user has the dataset locally, and no remote name is given, then it will return the local log list and never fetch from the registry. This means we have not given the user any way to explicitly fetch from the registry, bypassing local search, since we can neither indicate a remote name for the registry, and any boolean flag that defaults to false, so we can never actually understand the user's intention (did they set the flag false indicating `network only`, or did they never set a flag, indicating `search both`).

We really want to allow three different options:
1) only search local
2) only search network (remote, if it's selected, otherwise registry)
3) search local first, then network if it's not found (default)

Proposing we add a `network` flag that bypasses local search & immediately searches for the log on the network, using the remote name if it exists.

**Comment by ramfox** [comment]
Suggestion from @b5:
`remote=registry` means skip local and only search on the registry, rather than having a `network` flag

**Comment by b5** [comment]
After some more thought, I think we want `--remote=registry` _and_ a flag like the `--network` flag you proposed. I think we should name the flag `--pull`:

```
$ qri log --help
...
Flags:
  -p, --pull          fetch the latest logs from the network
```

I think the `pull` name works because _when you fetch logs for a dataset you have locally, it should retain those logs_. logbook is different from dataset versions in that it's _eager_. We always want to keep the latest version of dataset history we can get our hands on.

At the same time, qri CLI is an _offline first application_, meaning for data you're working on, qri shouldn't update things until you type `pull` somewhere. Desktop, on the other hand, has a network tab that's explicitly designed to skip this offline-first behavior. This distinction is intentional. Fetching more from the network creates a smoother experience for new users, but irritates power users, who prefer fine-grained control over network access.

Other notes:
* Using `--local` with either `--remote` or `--pull` should be an error
* Using `pull` with a dataset you _don't_ have is effectively a no-op. You don't have the dataset, so it _has_ to come from the network
*
