### ISSUE TITLE
feat(CLI): init CLI command should be able to work with existing files

### ISSUE THREAD

**Issue by uhLeeshUh** [qri-io/qri#1524]
### What feature or capability would you like?
Should be able to init a new Qri dataset with an existing file in the target directory

Feedback from user Paul Crickard in Sprint R: “I put my csv in a folder I made for the project before seeing that the next command added it. I was wondering if it was possible to run init with files already in and not using the flag like the example. I think I already have files in folders a lot of times when I start a project.”

**Comment by dustmop** [comment]
We do have the flag `qri init --source-body-path some-data.csv`. However, I think the flag name could maybe be better (perhaps just `--body`) and our documentation and tutorials probably don't mention it.

**Comment by b5** [comment]
I'm a fan of renaming the flag to `--body`, and then updating the documentation to point out you can do such a thing.  

We could get fancy & try to do this for the user, but I'm not sure it's worth it yet. So a few tasks to close this:

* [ ] rename qri init flag: `--source-body-path` -> `--body`
* [ ] make sure there's a test that works `qri init --body`, in the `cmd` package
* [ ] update the docs on this page: https://qri.io/docs/getting-started/qri-cli-quickstart to use the new `--body` flag

**Comment by dustmop** [comment]
Rereading the initial feedback: "I was wondering if it was possible to run init with files already in and not using the flag like the example". I may have missed this before, but by "not using the flag", does that mean just running `qri init` (no flags) and having the command guess which csv file in the current directory to use? That seems over-eager, but might be what a user expects if the directory only contains a single csv file. I don't think the command is especially clear that it will create new files, and users may expect that, like `git init`, qri can be used to version control any csv file in the directory, rather than the magic "body.csv" filename that we require.

**Comment by ramfox** [comment]
Yea I think the asked for feature is to recognize that there is a csv file and assume its the body, but I think b5 is scoping that down to "let's make it more clear what we expect and have the flag be simple".

**Comment by dustmop** [comment]
Sounds good! I agree that's a good first step, anything more complicated sounds like a separate feature that should be more purposefully designed.
