### ISSUE TITLE
`brew install qri`

### ISSUE THREAD

**Issue by osterbit** [qri-io/qri#158]
would be great to get the app on homebrew and add that as an option next to the download link on the website

**Comment by b5** [comment]
👍 let's tackle this once we clear through at least version 0.2

**Comment by andrew** [comment]
Here's a working formula for 0.7.3 that uses the prebuilt binary, that might not be accept into homebrew core (I believe they prefer from source builds) but could be added to a repo called https://github.com/qri-io/homebrew-qri, then users can run `brew install qri-io/qri/qri`.

For a from-source formula, you're probably better off waiting until #726 is done otherwise you have to declare every go dependency explicitly in the formula file.

```ruby
class Qri < Formula
  desc "A global dataset version control system (GDVCS) built on the distributed web"
  homepage "https://qri.io/"
  url "https://github.com/qri-io/qri/releases/download/v0.7.3/qri_darwin_386.zip"
  version "0.7.3"
  sha256 "195480ebad83402d73a90a1c0b17d529298594d108da5ec336abb8f1a77b88ce"

  def install
    bin.install "qri"
  end

  test do
    system "#{bin}/qri", "setup", "-a"
  end
end
```

**Comment by dustmop** [comment]
Cool, thanks for providing this example! I'll look into setting this up, agreed that it would be super useful to have this working in order to help introduce qri to new users.

**Comment by dustmop** [comment]
Implemented by https://github.com/qri-io/qri_install/pull/6 and https://github.com/qri-io/qri_install/pull/7, now just need to update the docs. Closing this issue.
