### ISSUE TITLE
readme component returned by `Get` should contain text of the file

### ISSUE THREAD

**Issue by dustmop** [qri-io/qri#1826]
One of the outstanding items on our fixit is concerning `qri get`: "readme isn’t populated". The root cause of the issue is that "file components", such as transform, viz, and readme, keep their files as "script" objects that only contain the path to the underlying file. Fixing this could be solved by just inlining the script contents for each of these components.

Is there any reason we don't want to always inline these 3 components in the `dataset.Get` method? It seems like all of these components are going to contain small files most of the time (we're probably a ways away from having large transform scripts showing up).

My proposal would be to modify `dataset/transform.go` and `dataset/readme.go` and `dataset/viz.go` so that each component has a `Text string` field that contains the plain text of the file.

Fixing this should also solve a number of related issues:
* https://github.com/qri-io/qri/issues/1578
* https://github.com/qri-io/qri/issues/1339

**Comment by b5** [comment]
> Is there any reason we don't want to always inline these 3 components in the dataset.Get method?

If the selector doesn't path into one of these three components, we shouldn't be opening those components. As a user I'd be surprised if you told me  `qri get body user/dataset` also loaded the readme, transform and viz.

On the other hand, when I `get` a dataset without any selector, I do expect a balance of complete and concise. `get` without a selector _should_ be giving the user readme & transform overviews if they exist,  which is why we're switching to `qri get user/dataset` returning a preview. Previews can and should be cached.

> My proposal would be to modify dataset/transform.go and dataset/readme.go and dataset/viz.go so that each component has a Text string field that contains the plain text of the file.

I'm bringing up previews here because they do something very close to what you're proposing for the readme component:

https://github.com/qri-io/dataset/blob/917fdaf703330a23a0dc98002881343503133ab7/preview/preview.go#L64-L79

The biggest difference: `ScriptBytes` is of type `[]byte` and your proposal of `Text` would be of type `string`. The problem with the byte slices shows up when serialized to JSON, where `ScriptBytes` ends up as a long string of base64 encoded gak, illegible to humans.

All this is to say: **there is a lot of overlap between your proposed `Text` field and `ScriptBytes`**. So I'd propose _removing_ `ScriptBytes []byte` and replacing it with either `Text string` or `Script string`. in the three spots you've mentioned.

* We use `ScriptBytes` when [inlining files into components](https://github.com/qri-io/dataset/blob/917fdaf703330a23a0dc98002881343503133ab7/readme.go#L75-L95), but there's no reason we can't back this with a string instead of a slice of bytes.
* ScriptBytes is a _transient_ field, and should never have been written to IPFS, so we're safe to alter this field & maintain backward compatibility. 
* The new field should also be marked as transient and all `DropTransientField` functions should assign `Text` to the empty string
* when serialized to JSON `Text` should `omitempty`.

**Comment by dustmop** [comment]
> > Is there any reason we don't want to always inline these 3 components in the dataset.Get method?
> 
> If the selector doesn't path into one of these three components, we shouldn't be opening those components. As a user I'd be surprised if you told me `qri get body user/dataset` also loaded the readme, transform and viz.
> 

Right, I meant to specify "without a selector" in my original post. That semantically means "give me everything" which means it's reasonable to expect expanding file components.

> All this is to say: **there is a lot of overlap between your proposed `Text` field and `ScriptBytes`**. So I'd propose _removing_ `ScriptBytes []byte` and replacing it with either `Text string` or `Script string`. in the three spots you've mentioned.
> 
> * We use `ScriptBytes` when [inlining files into components](https://github.com/qri-io/dataset/blob/917fdaf703330a23a0dc98002881343503133ab7/readme.go#L75-L95), but there's no reason we can't back this with a string instead of a slice of bytes.
> * ScriptBytes is a _transient_ field, and should never have been written to IPFS, so we're safe to alter this field & maintain backward compatibility.
> * The new field should also be marked as transient and all `DropTransientField` functions should assign `Text` to the empty string
> * when serialized to JSON `Text` should `omitempty`.

I'm good with all of this. I couldn't remember if there was a reason `ScriptBytes` was originally using the `[]byte` type instead of string, but it was perhaps because we expected to store arbitrary file content? Turns out that hasn't happened and file components so far have always been textual.

I don't think this needs to be done in two phases, and the replacement can all happen at once, but I'll give it a shot and see exactly how much work is involved.
