### ISSUE TITLE
qri connect / data add issues

### ISSUE THREAD

**Issue by ebenp** [qri-io/qri#235]
Seeing the following issues when I try to add data or connect. Does a port have to be open?
eben$ qri add me/largest_rivers.csv
INFO[0002] connecting to the distributed web...         
error getting peer IPFS id: datastore: key not found

eben$ qri connect
INFO[0001] boostrapping to: QmNX9nSos8sRFvqGTwdEme6LQ8R1eJ8EuFgW32F9jjp2Pb 
attempting to add default dataset: me/comic_characters@/ipfs/QmcqkHFA2LujZxY38dYZKmxsUstN4unk95azBjwEhwrnM6/dataset.json
INFO[0001] connecting to qri:
  peername: ep
  QRI ID: QmVCXRiqFiyHEYYyT1PnJ44vKUj7eZTRYycc37nzWuNU5q
  API port: 2503
  IPFS Addreses:
  /ip4/127.0.0.1/tcp/4001/ipfs/QmdmgTY9897E6qSbwwmaWkmxc3PcpDMpoPgxA4BDGF3YBh
  /ip4/192.168.0.112/tcp/4001/ipfs/QmdmgTY9897E6qSbwwmaWkmxc3PcpDMpoPgxA4BDGF3YBh
  /ip6/::1/tcp/4001/ipfs/QmdmgTY9897E6qSbwwmaWkmxc3PcpDMpoPgxA4BDGF3YBh 
INFO[0001] accepting RPC requests on port 2504          
INFO[0001] error connecting to host: dial attempt failed: misdial to <peer.ID NX9nSo> through /ip4/130.211.198.23/tcp/4001 (got <peer.ID NvaJr7>): read tcp 192.168.0.112:4001->130.211.198.23:4001: use of closed network connection 
21:15:28.874 ERROR       mdns: mdns lookup error: failed to bind to any multicast udp port mdns.go:140

**Comment by b5** [comment]
@ebenp! Thanks for filing good sir. We don't have great documentation for this quite yet, but I'm guessing you're working with a CSV file `largest_rivers.csv`. If that's the case, you'd want to use this command: 
```sh
$ qri add --data largest_rivers.csv me/largest_rivers
```
which saying "I want to create a dataset named largest_rivers" from the file `largest_rivers.csv`, qri should be much happier with that. When we run `qri add` without any flags:

```
$ qri add me/largest_rivers.csv
```
That's the equivalent of saying "I want to add a dataset named `largest_rivers.csv` owned by peer `me`". Given that me is _you_, qri checks your local repo, sees nothing, and assumes you're talking about data you're storing somewhere on the distributed web, so it connects to try to find it.


`qri help add` should hopefully provide some useful examples to follow as well.

As for the `qri connect` issue, well that's a whole 'nother mess, and a bug. if you try running `qri connect` again in the future and see things like this bit:
```
INFO[0001] error connecting to host: dial attempt failed: misdial to <peer.ID NX9nSo> through /ip4/130.211.198.23/tcp/4001 (got <peer.ID NvaJr7>): read tcp 192.168.0.112:4001->130.211.198.23:4001: use of closed network connection
21:15:28.874 ERROR mdns: mdns lookup error: failed to bind to any multicast udp port mdns.go:140
```
I'd love to know. Because that's us improperly configuring bootstrap nodes on our end. But, there's a chance we've fixed it since you last tried.

Lemmie know if that helps!

**Comment by ebenp** [comment]
Hey @b5 Thanks for that great explanation. Let me know in the future if you need help with documentation.  I rebuild qri from source and still get the below. Let me know what other testing I can help with on this.

`eben$ qri connect
INFO[0002] boostrapping to: QmNX9nSos8sRFvqGTwdEme6LQ8R1eJ8EuFgW32F9jjp2Pb 
attempting to add default dataset: me/comic_characters@/ipfs/QmcqkHFA2LujZxY38dYZKmxsUstN4unk95azBjwEhwrnM6/dataset.json
INFO[0002] connecting to qri:
  peername: ep
  QRI ID: QmT2H7w6km6db5H7XKVJGz1krJX77AxHZ2iBnLGy7bPsts
  API port: 2503
  IPFS Addreses:
  /ip4/127.0.0.1/tcp/4001/ipfs/QmdmgTY9897E6qSbwwmaWkmxc3PcpDMpoPgxA4BDGF3YBh
  /ip4/192.168.0.103/tcp/4001/ipfs/QmdmgTY9897E6qSbwwmaWkmxc3PcpDMpoPgxA4BDGF3YBh
  /ip6/::1/tcp/4001/ipfs/QmdmgTY9897E6qSbwwmaWkmxc3PcpDMpoPgxA4BDGF3YBh 
INFO[0002] accepting RPC requests on port 2504          
INFO[0003] error connecting to host: dial attempt failed: misdial to <peer.ID NX9nSo> through /ip4/130.211.198.23/tcp/4001 (got <peer.ID NvaJr7>): read tcp 192.168.0.103:4001->130.211.198.23:4001: use of closed network connection 
19:50:03.578 ERROR       mdns: mdns lookup error: failed to bind to any unicast udp port mdns.go:140`

**Comment by ebenp** [comment]
closing this as add works, no change to the connect error in 0.1.1. I still get it.

**Comment by b5** [comment]
makes sense, we still have some work to do on `connect`, should have an update on that come Monday of next week. Thanks @ebenp!

**Comment by ebenp** [comment]
As a followup I was still getting this issue and seem to have got around it by upping the file limit following the comment here:
https://github.com/ipfs/support/issues/17

**Comment by b5** [comment]
Innnnteresting. I hadn't read your error output carefully enough. We had a separate issue that was causing misdials to bootstrap peers, but this wasn't the error I had in mind.

That alone might be worth working into our documentation. Specifically this part of the error that you were previously getting:
```
ERROR mdns: mdns lookup error: failed to bind to any unicast udp port mdns.go:140
```
Since you found it I'd love to get you the contributor points if you're interested in becoming our second outside contributor 😄. I'd welcome a PR that:

* [ ] creates a new file at the root of this repo: `troubleshooting.md`
* [ ] says "if you see errors along these lines: `ERROR mdns: mdns lookup error: failed to bind to any unicast udp port mdns.go:140 ...`, check out ipfs/support#17", feel free to massage the language or provide details that you followed to help others
* [ ] adds a reference in README.md pointing newcomers to `troubleshooting.md` for possible fixes to common issues.

@machawk1 has also helped identify some other issues that'd be a great fit for this sort of file :)

Thanks again @ebenp, we're super grateful that you're taking the time to play with qri and tell us about it

**Comment by ebenp** [comment]
Sounds good. @b5 and @machawk1 I've opened https://github.com/qri-io/qri/pull/321
