### ISSUE TITLE
Question about GetDataset vs LoadDataset

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#238]
Hello!

So it seems like repo.GetDataset loads a datasets from a file, iterates through to find the one specified. If it's not found, then it calls dsfs.LoadDataset to try and load it from the filestore.

So does this mean we should be calling GetDataset instead of LoadDataset in most places? What are the subtleties I'm missing?

Is it that GetDataset doesn't dereference anything? So if we want guaranteed dereferencing we need to call LoadDataset?

**Comment by b5** [comment]
`repo.GetDataset` and `dsfs.LoadDataset` are two closely related functions that are intended to operate at different levels in the software stack. 

Basically, `repo` implementations are supposed to use `dsfs.LoadDataset`, and everyone else is supposed to use `repo.GetDataset`. This is because in the future we'll have datasets coming from a number of different places (for example, a cache of recently-loaded datasets), and each `repo` implementation will need to make.

We have `dsfs.LoadDataset` because repos are intended to be wrapped around a `cafs.Store`, `dsfs.LoadDataset` makes the process of getting a dataset out of a store uniform. repos should _not_ implement their own `LoadDataset` functionality unless absolutely necessary.

**Comment by ramfox** [comment]
Okay dope. So from my understanding:

repo is allowed to talk to dsfs, no one else should. Use repo.GetDataset unless you are in the repo package, which is allowed to talk to dsfs.

**Comment by b5** [comment]
exactly. That's where we're headed. When you see code that uses dsfs without going through a repo, it should be refactored to work with a repo instead.
