### ISSUE TITLE
add from peer won't work if the dataset name matches one already in your repo

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#246]
So qri won't let you add a peer's dataset to your repo, when that dataset has the same name as a dataset already in your repo.

I'm assuming we just give the user a place to add their preferred name. 

Does changing the name of this repo somehow mess something up? We will still have the history of the dataset, as long as we don't change the PreviousPath, correct?

If they don't add their preferred name, we should error, correct? Not save the repo as [datasetname]_1 or [peername]_[datasetname]?

Thoughts?

**Comment by b5** [comment]
do you have output from what happens when you try to do this?

**Comment by ramfox** [comment]
```
qri add ramfox_2/cities_2
INFO[0001] connecting to the distributed web...
error putting dataset name in repo: repo: name already in use
```

**Comment by b5** [comment]
Oh wow look we even gave, like, a readable error message there.

Generally, that's the reason we need to _namespace using peernames_. But currently we don't handle that properly. This is tangentially related to #220 in that both this issue and the `/dataset.json` problem come from us not properly storing references. In practice this means we need to ship a PR that adjusts [fs namestore](https://github.com/qri-io/qri/blob/master/repo/fs/namestore.go) to be a sorted slice of references.

I'll ship a PR for both now, mainly because this is irritating.

**Comment by ramfox** [comment]
Okay cool! So I'll pause on this for now. Thanks!!!
