### ISSUE TITLE
yaml should be our default export format for everything that isn't the body/data fight me

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#426]
Since our `qri add --dataset` flag accepts a yaml file, and our qri config lives naturally in yaml, yaml should be our default format for everything except for the dataset body/data.

**Comment by b5** [comment]
FINE. FAK.

**Comment by b5** [comment]
lol but in all seriousness, yes. I like the idea of the outside world conceiving our our dataset/webpage as a .yaml file. We should encourage this by working with dataset pages by default. 

This also makes me want to change our silly `file` flag to `dataset` to a) not use the word `file`, and b) reinforce this notion that `dataset.yaml` *is* a dataset in userland.

**Comment by ramfox** [comment]
Yes I think changing `--file` to `--dataset` es muy bueno

**Comment by ramfox** [comment]
To be clear, changing our defaults to yaml would mean having yaml be the default for:

* all export commands (structure, meta, dataset)
* all config commands, including the ones that just print to the console

**Comment by b5** [comment]
* default yaml across the board
* `all` and `dataset` flags should be removed
* running a raw `qri export me/foo` should:
  * create a directory  `me/foo` (bail if directory already exists)
  * create a `dataset.yaml` inside that directory of all the stuff
  * create a `data` file who's extension matches `dataset.Structure.Format` _unless_ `--body-format` says otherwise
* `namespaced` should be replaced with `--no-dir`, which now does the opposite (new default is to write to a directory), and just writes whatever's being exported to the PWD
* new `--format` flag description: `set export format (except for dataset body)`
* later we should upgrade `dsutil.WriteZipArchive` to accept these `--format` and `--body-format` configuration settings to alter the created zip directory. In the meantime setting the `--zip` flag should just let `dsutil.WriteZipArchive` do it's thing
* bonus points: add a `schema` flag that just exports `ds.Structure.Schema` in the same manner as `--meta` and `--structure`
