### ISSUE TITLE
qri install process didn't work

### ISSUE THREAD

**Issue by Frijol** [qri-io/qri#618]
I used the installer for the cli per at http://qri.io/docs/tutorials/cli_quickstart/#1.0 (following this address for the installer download: https://github.com/qri-io/qri/releases/download/v0.6.0/qri_os_x_cli_darwin_amd64.pkg).

The installer completed with no errors, but:

```sh
➜  ~ qri
zsh: command not found: qri
```

(I also tried it in regular terminal to the same effect, so it's not my zsh)

I'm on OSX Mojave 10.14.1

**Comment by b5** [comment]
Hey @Frijol! Are you running os X Mojave by chance?

**Comment by Frijol** [comment]
yep!

**Comment by b5** [comment]
oops, you literally posted that in your issue. my bad.

Ok, yes I think this is a mojave issue. I'm filing as a bug and will try to get a fix going. I'm having the same issue with the installer since upgrading

**Comment by b5** [comment]
Ok, so while I work on getting a proper fix in place, this one-liner will get you up & running:
```
$ cd /usr/local/bin
$ sudo ln /usr/local/qri/bin/qri qri
```
*This command uses super-user priviledges* (the sudo part). It will only work because you've already run the Qri installer. This command creates a symbolic link between where the installer put qri (`/usr/local/qri/bin/qri`), and a place where your system can find it (`/usr/local/qri`). I've intentionally written this with a `cd` command to avoid accidentally linking weird stuff. 

you'll know it's working when `$ qri` works 😄. I'll work on getting the installer to function better so others don't have to run these commands.

If you need to reverse this linking, run:
```
$ cd /usr/local/bin
$ sudo rm qri
```
be _very_ careful when typing that second command in

**Comment by Frijol** [comment]
oh I just built it from source & am up and running. Is it useful for me to test local linking? Thanks!

**Comment by b5** [comment]
Lol nope, that’s just a temp fix and has little value. Glad you could build from source!

**Comment by Frijol** [comment]
(hm, I'm also commenting your docs but from `0.6.1-dev`. Going to keep doing that so you have a record of docs audit for when that version goes live but heads up for when you review the issues & PR..)

**Comment by b5** [comment]
quick update on this, fixing the installer is going to take some work. As far as I can tell the same issue is present in the golang installar our process is based on. I've filed an issue there: https://github.com/golang/go/issues/28901

It'll be some time before we get this fixed, I'm guessing at least a month

**Comment by b5** [comment]
we no longer use this installer. Instead the fastest way to install qri is with: 
`curl -fsSL https://qri.io/install.sh | sh`
