### ISSUE TITLE
`qri connect` not working (I think)

### ISSUE THREAD

**Issue by Frijol** [qri-io/qri#623]
trying out `qri connect` (I'm on 0.1.6-dev version). Following tutorial & doing this for the first time, so not 100% sure I'm executing correctly, but I think I am.

```sh
➜  nalcs_standings qri connect
17:21:20.825  INFO     qrip2p: boostrapping to: QmTZxETL4YCCzB1yFx4GT1te68henVHD1XPQMkHZ1N22mm bootstrap.go:27
17:21:20.825  INFO     qriapi:
peername:	frijol
profileID:	QmXMbo6XWE7C46sgFq1TjTf5KTq74ufYnmhW5Y9VPbFCrx
API port:	2503
RPC port:	2504
Webapp port:	2505
IPFS Addresses:
  /ip4/127.0.0.1/tcp/4001/ipfs/QmNwTk2tb6ppHQmgywiQsDQimrS6APBiNT4UU16jAZh9Zv
  /ip4/192.168.254.50/tcp/4001/ipfs/QmNwTk2tb6ppHQmgywiQsDQimrS6APBiNT4UU16jAZh9Zv
  /ip6/::1/tcp/4001/ipfs/QmNwTk2tb6ppHQmgywiQsDQimrS6APBiNT4UU16jAZh9Zv api.go:98
2018/11/20 17:21:20 rpc.Register: method "CoreRequestsName" has 1 input parameters; needs exactly three
17:21:20.827  INFO     qrip2p: boostrapping to: QmUUVNiTz2K9zQSH9PxerKWXmN1p3DBo3oJXurvYziFzqh bootstrap.go:27
17:21:20.827  INFO     qrip2p: boostrapping to: QmNX9nSos8sRFvqGTwdEme6LQ8R1eJ8EuFgW32F9jjp2Pb bootstrap.go:27
2018/11/20 17:21:20 rpc.Register: method "CoreRequestsName" has 1 input parameters; needs exactly three
2018/11/20 17:21:20 rpc.Register: method "CoreRequestsName" has 1 input parameters; needs exactly three
2018/11/20 17:21:20 rpc.Register: method "CoreRequestsName" has 1 input parameters; needs exactly three
2018/11/20 17:21:20 rpc.Register: method "CoreRequestsName" has 1 input parameters; needs exactly three
2018/11/20 17:21:20 rpc.Register: method "CoreRequestsName" has 1 input parameters; needs exactly three
2018/11/20 17:21:20 rpc.Register: method "CoreRequestsName" has 1 input parameters; needs exactly three
2018/11/20 17:21:20 rpc.Register: method "CoreRequestsName" has 1 input parameters; needs exactly three
17:21:20.828  INFO     qrip2p: boostrapping to: QmP6sbnHXANXgQ7JeCCeCKdJrgpvUd8s75YNfzdkHf6Mpi bootstrap.go:27
17:21:20.858  INFO     qriapi: updating webapp to version: /ipfs/QmWN12oSKHCoZpkuSeLhB1qH2VaRG43p78hRDFL3Zz5sfU webapp.go:58
```

This hangs forever (which I expected, as it should run a node) but possibly that lower part of the logging indicates fail errors?

In a separate terminal window, while that is running, I tried `qri peers`

```sh
➜  ~ qri peers

The `peers` commands allow you to interact with other peers on the Qri network.
In order for these commands to work, you must be running a Qri node. This
node allows you to communicate on the network. To spin up a Qri node, run
`qri connect` in a separate terminal. This will connect you to the network,
until you choose to close the connection by ending the session or closing
the terminal.

Usage:
  qri peers [command]

Available Commands:
  connect     Connect to a peer
  disconnect  Explicitly close a connection to a peer
  info        Get info on a Qri peer
  list        List known qri peers

Flags:
  -h, --help   help for peers

Use "qri peers [command] --help" for more information about a command.
```

I assume that's the output you'd get if you didn't have `qri connect` running.

**Comment by ramfox** [comment]
Hi! Thanks for the update. I haven't noticed that output before, but it looks like it's happening on my machine as well, but everything is still working properly. So you are connected!!! :)

The reason the `qri peers` command is giving you the help output rather then doing anything useful, is it requires a third command in order to function, eg `qri peers list` to get the list of peers you are currently connected to, or `qri peers info [peername]` to get details about a specific peer that you are connected to.

Now about the error, @b5  would love some help:

The "rpc.Register: method "CoreRequestsName" has 1 input parameters; needs exactly three" comes when we attempt to register each Request struct in the lib package:

https://github.com/qri-io/qri/blob/3f8368f9c832bb61969a3d1f7669d8aa5e7d91ca/api/api.go#L113-L134

In line 125, we try to register all the lib methods on each Request struct. However, each Request struct also contains a `CoreRequestsName` function, that does not follow the needed RPC method signature (receiver, *args, *reply). So Registering `CoreRequestsName` function fails once for each Request struct (8 times). This seems to have always been happening, but maybe something has changed with the logging recently to make it actually show up.

I'm not sure how to fix this except to remove CoreRequestsName() function from each Request, or have CoreRequestsName() satisfy the rpc method signature.

Also this:
https://github.com/qri-io/qri/blob/3f8368f9c832bb61969a3d1f7669d8aa5e7d91ca/lib/lib.go#L18-L23

Did this interface used to be called `CoreRequests`?

**Comment by dustmop** [comment]
I think these messages about `CoreRequestsName` are harmless, and are being caused by a recent upgrade to a new version of go, or one of our dependencies. The go core added this error message [here](https://github.com/golang/go/commit/a89fa7040bdccd0531aa51eb7c8c83f6fa36df25#diff-b89fcc7b0ca3255b98242fedd56a02d4), whenever it finds a method on an registering interface that doesn't match their spec (2 out parameters, 1 return value). However, according to the docs for [rpc](https://golang.org/pkg/net/rpc/), such methods should simply be ignored. We've been relying on this fact up til now to use `CoreRequestsName` as a way to get a nice name for a library object, without it being exported over rpc.

Perhaps there's a way to silence this warning, because it's useless to us. I'll dig in...

**Comment by Frijol** [comment]
Oh! That makes sense, tried `qri peers list` and it works great. Thanks for the assist.
Mild suggestion: might be helpful to have a clear "Success" message when `qri connect` is ready!
