### ISSUE TITLE
YAML export problem

### ISSUE THREAD

**Issue by WaughB** [qri-io/qri#652]
Going through the tutorial in section 2.2 I tried to reproduce the YAML file for the nalcs_standings dataset. After running:
```bash
qri export --format yaml me/nalcs_standings
```
The resulting zip folder still had a JSON in it.
I also tried running:
```bash
qri export -f yaml me/nalcs_standings
```
and received the same output. 
The resultant zip folder did contain the body.csv, dataset.json, and ref.txt but did not produce a YAML. 

Running:
```bash
qri export --blank me/nalcs_standings 
```
did produce the blank YAML file.

**Comment by dustmop** [comment]
This is definitely my bug. The export function is pretty bare-bones at the moment, because it was implemented in a bit of a rush, and I believe it ignores the format parameter (oops) to always use json. Can fix this tomorrow.

**Comment by dustmop** [comment]
Ok, this has been mostly fixed by https://github.com/qri-io/qri/pull/656. There's still more work to be done, but at least now, unsupported flags throw an error, and supported flags do what they say they do.

To export a dataset like you were trying before, use `qri export --format yaml --zip me/nalcs_standings`. You'll get a zip with the main dataset file as dataset.yaml. Future support will include exporting as a raw yaml or json file without being in a zip, as well as control over the body format.

**Comment by dustmop** [comment]
Export functionality was fixed awhile ago, just forgot to update this issue. https://github.com/qri-io/qri/pull/688 completely overhauled export, and https://github.com/qri-io/qri/pull/693 was a follow-up to fix some functionality for zip outputs.

Running `qri export --format yaml me/nalcs_standings` now will output a single-file yaml dataset, while you can get a zip (containing a yaml description of the dataset) using `qri export --format yaml --zip me/nalcs_standings`.
