### ISSUE TITLE
Linux- "error setting max open files limit: operation not permitted" when calling qri in CLI

### ISSUE THREAD

**Issue by grant0711** [qri-io/qri#678]
Each time when calling qri in the command line on linux, the following message kept appearing as output:

"error setting max open files limit: operation not permitted"

Followed by the correct output of the command that was being called.

To remove this, I visited the following thread to troubleshoot:

https://superuser.com/questions/1200539/cannot-increase-open-file-limit-past-4096-ubuntu

The solution that worked for me was to go into two conf files to modify:

/etc/systemd/user.conf
/etc/systemd/system.conf

With sudo nano, scroll down to "#DefaultLimitNOFILE=" and modify to "DefaultLimitNOFILE=10000".

After rebooting and checking "ulimit -n" it is now set to 10000 and qri commands no longer produce the error.

**Comment by b5** [comment]
@dustmop you've also run into this max-open files problem. Mind combining @grant0711's instructions with what you've learned into a PR that adds a section on `open file limits` to `troubleshooting.md`?

**Comment by dustmop** [comment]
Finally looked into this. It seems like the file limit problem isn't as big of an issue on linux, and the error can just be safely ignored. Qri works fine even if Setrlimit fails. I'm going with https://github.com/qri-io/qri/pull/750 for now, and if this because a problem after more testing on linux, we can revisit this later.
