### ISSUE TITLE
Exposing `offset` and `limit` as flags/params on api `/body`

### ISSUE THREAD

**Issue by ramfox** [qri-io/qri#766]
### ~Exposing `offset` and `limit` as flags/params on api and cmd~

~We recently unified all the API and cmd endpoints to take page and page-size. We recognize though, that for some use cases using limit and offset are an order of magnitude simpler! Let's add those as advanced flags, that will exist, but will not be the primary focus in our documentation. As per this [code conventions issue](https://github.com/qri-io/qri/issues/761#issuecomment-490535806), an offset of 0 and a limit of -1 will return the entire list.~

~If either or limit or offset are set, they will override the page and page-size flags.~

### Exposing `offset` and `limit` as flags/params on api `/body`
As per below, we are scoping this issue down to include `offset` and `limit` params for only the `/body` endpoint!

An offset of 0 and a limit of -1 will return the entire list.

**Comment by ramfox** [comment]
hey, quick q about how we think defaults should work.

So `limit = -1` and `offset = 0` mean give me everything.

Would defaulting to setting the `limit` and `offset` flags on the cmd as `limit = -1` `offset = -1`, be too flimsy? Meaning, all the user would have to do is set `offset = 0` to get the effect of returning everything. Or is this the behavior we intent?

Thinking about having the default be `limit = 0`, `offset = -1`, that way the user would have to set both of the flags explicitly. But this might be overkill. Thoughts?

**Comment by b5** [comment]
I think the answer is different depending on the environment:

### Streaming (CLI)
In a streaming context we want to default to no pagination at all. the "interface" is a stream of bytes we consume from. Thanks to our work with `$PAGER`, we can literally be fetching more data as the user scrolls through results. If at some point they stop reading from the stream, we know to stop "paging".

In this context the "opt in" is pagination. There are lots of cases where I'll want to artificially clamp output, and in that context I think `page` and `page-size` should be plenty fine.

I call this a "streaming" context because this also applies to situations like libp2p connections (which are duplex streams, and websockets.

### Request-Response (HTTP)
In a Request-Response context like HTTP, we don't have the luxury of a continuous feedback loop, so we should default to pagination, telling the server in advance the maximum number of items we'd like from the list, and the `limit` figure uses some sensible default number like `25`, but can be adjusted. The opt-in case is the _entire list_. 

To that end, we don't want to make "request all" available in all contexts (public, hosted APIs will grind to a halt if too many people use a feature like this). So we'll want to be careful when exposing this. For example setting `config.API.readOnly: true` should disable limit/offset params.

I call this request-response because this also applies to our RPC communication layer. Basically anywhere when you can't continuously converse with the source of data

** **
@ramfox & I discussed this offline, and for now the place we really need `limit` and `offset` params is in a situation where **pageSize needs to dynamically change in a request-response context**. Basically, dataset bodies over HTTP.

This is a big issue when loading dataset body data, where we want to be able to present buttons for loading the next 10, 100 or 1000 rows. This is also the _only_ place we're doing varied page-sizes for request-response, so we're only going to add `limit` & `offset` params for the `/body` api endpoint as an experiment. If the need arises in other places, we have a pattern ready for use.
