### ISSUE TITLE
cmd.printInfo Output is Nearly Invisible on Light Terminals

### ISSUE THREAD

**Issue by Mr0grog** [qri-io/qri#771]
I tried running `qri version` and went absurdly deep trying to figure out why it was printing a blank line in my terminal:

<img width="284" alt="qri blank line" src="https://user-images.githubusercontent.com/74178/58004954-51a71480-7a99-11e9-9b45-b232d33fd790.png">

However, it turned out the line wasn’t blank at all! It’s just white, and my terminal’s background is very light. If I select the text, I can see it:

<img width="262" alt="qri highlighted line" src="https://user-images.githubusercontent.com/74178/58004996-78fde180-7a99-11e9-847b-478a458fd0d5.png">

This is happening because the `version` command uses `cmd.printInfo`, which explicitly sets the color to white: https://github.com/qri-io/qri/blob/9ae8d44df443608c487b5269789181b87988496b/cmd/print.go#L43-L45

I think it might be better to use `color.Reset` instead of `color.FgWhite` for this case, though I’m not sure whether that might cause problems in other places where we call this function (e.g. if it might cause problems when nested inside another colored string or something). I’m happy to make a quick PR for this if that’s not likely to be an issue, though.

**Comment by b5** [comment]
Ugh, nice find. This clearly needs to be fixed, and we might as well do it properly & audit all uses of the color package for these hard-coded colours like `FgWhite` `FgGreen`.  Only two files on current master should need auditing:

* https://github.com/qri-io/qri/blob/master/cmd/print.go
* https://github.com/qri-io/qri/blob/master/cmd/stringers.go
* https://github.com/qri-io/qri/blob/master/cmd/diff.go (use of the `color` package in this file should be moved into `stringers.go`)



I'm going to assign myself for the work because I'd like to do a more thorough job than I can reasonably ask of you @Mr0grog. If you have any interest in PR review, I'd be happy to have it 😄

**Comment by Mr0grog** [comment]
Makes sense! Happy to give any feedback once you have things mostly done :)
