### ISSUE TITLE
After commit adding meta via fsi, status shows 'modified'

### ISSUE THREAD

**Issue by chriswhong** [qri-io/qri#850]
![meta_json_—___datasets_Billboard_Hot100_1964_and_Qri_Desktop_and_Sprint_O](https://user-images.githubusercontent.com/1833820/62076837-a9d76100-b216-11e9-8db2-9e0708fe1098.png)

After saving a new `meta.json` with a lone `title` key, `/dsstatus` reports `meta.json` as modified, seemingly due to the existence of `qri` key which is probably supposed to be hidden.

**Comment by dustmop** [comment]
This is the same as point #3 in https://github.com/qri-io/qri/issues/837 ("running qri save while connected..."). I believe this is in fact due to a missing "keyword: []" value, not the "qri" key, and is somehow caused by god encoding while serializing the Meta over rpc. Need to investigate further.

**Comment by dustmop** [comment]
Can't reproduce this anymore. I think @b5's recent refactorings may have fix it. When you get a chance, could you try running with the qri binary at head and see if its still happening?

**Comment by chriswhong** [comment]
I can't reproduce either, closing
